# Generated by Django 3.1.7 on 2021-10-11 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_comment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='bookmark',
        ),
        migrations.AddField(
            model_name='blog',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
