# Generated by Django 3.1.7 on 2021-10-11 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211011_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='favorite',
        ),
    ]
